[package]
name = "rustdown"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
eframe = { version = "0.33", default-features = false, features = [
  "glow",
] }
egui_commonmark = { version = "0.19.0", default-features = false, features = ["pulldown_cmark", "load-images"] }
pulldown-cmark = "0.12"
rfd = "0.15"
imara-diff = { version = "0.2.0", default-features = false }
notify = "8.0.0"
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "gif", "webp", "bmp", "ico"] }

[target.'cfg(target_os = "linux")'.dependencies]
eframe = { version = "0.33", default-features = false, features = [
  "glow",
  "wayland",
  "x11",
] }
